#!/usr/bin/env python3
"""Rasterises the travel icons into an LVGL A8 header.

There is no icon font here with a train or a bus in it, and building one needs a
node toolchain that is not on this machine. These are a few rectangles and
circles instead, sampled sixteen times a pixel so the curves do not stair-step.
Alpha only: the panel recolours them, the same way it recolours the map.
"""
import pathlib

SIDE = 22
SUB = 4


def rounded(x0, y0, x1, y1, r):
    def inside(x, y):
        if not (x0 <= x <= x1 and y0 <= y <= y1):
            return False
        cx = min(max(x, x0 + r), x1 - r)
        cy = min(max(y, y0 + r), y1 - r)
        return (x - cx) ** 2 + (y - cy) ** 2 <= r * r
    return inside


def disc(cx, cy, r):
    return lambda x, y: (x - cx) ** 2 + (y - cy) ** 2 <= r * r


def render(solid, holes):
    out = bytearray()
    for py in range(SIDE):
        for px in range(SIDE):
            hit = 0
            for sy in range(SUB):
                for sx in range(SUB):
                    x = px + (sx + 0.5) / SUB
                    y = py + (sy + 0.5) / SUB
                    if any(s(x, y) for s in solid) and not any(h(x, y) for h in holes):
                        hit += 1
            out.append(round(255 * hit / (SUB * SUB)))
    return bytes(out)


# A carriage seen from the side: a rounded roof, a deep windscreen, a skirt over
# the bogies, and a gap under it so the wheels read as wheels.
TRAIN = render(
    solid=[rounded(5, 1, 17, 15, 4),       # body, roof rounded
           rounded(4, 14, 18, 16.5, 1),    # skirt
           rounded(6.5, 18, 9.5, 20.5, 1), # near bogie
           rounded(12.5, 18, 15.5, 20.5, 1)],
    holes=[rounded(6.5, 3.5, 15.5, 9, 2),  # windscreen
           rounded(10.6, 3, 11.4, 9.5, 0), # its centre pillar
           rounded(7, 10.5, 9, 13, 0.5),   # door
           rounded(13, 10.5, 15, 13, 0.5)],
)

# A bus is longer, flatter and sits lower, with a row of windows rather than one
# screen: that difference is what has to read at this size.
BUS = render(
    solid=[rounded(1, 4, 21, 15, 2),
           rounded(1, 14, 21, 16.5, 1),
           rounded(4, 18, 7, 20.5, 1),
           rounded(15, 18, 18, 20.5, 1)],
    holes=[rounded(2.5, 5.5, 8, 9.5, 1),
           rounded(9.5, 5.5, 15, 9.5, 1),
           rounded(16.5, 5.5, 19.5, 9.5, 1),
           rounded(2.5, 11, 19.5, 11.8, 0)],
)

def emit(name, data):
    rows = []
    for at in range(0, len(data), 16):
        rows.append("    " + " ".join(f"0x{b:02x}," for b in data[at:at + 16]))
    body = "\n".join(rows)
    return f"""
const std::uint8_t {name.upper()}_PIXELS[] = {{
{body}
}};

const lv_image_dsc_t {name.lower()}_icon = {{
    .header = {{.magic = LV_IMAGE_HEADER_MAGIC,
               .cf = LV_COLOR_FORMAT_A8,
               .flags = 0,
               .w = {SIDE},
               .h = {SIDE},
               .stride = {SIDE},
               .reserved_2 = 0}},
    .data_size = sizeof({name.upper()}_PIXELS),
    .data = {name.upper()}_PIXELS,
    .reserved = nullptr,
}};
"""


out = pathlib.Path(__file__).resolve().parent.parent / "components/ui/travel_icons.h"
out.write_text(f"""#pragma once

// Generated by tools/make_icons.py -- do not edit.

#include "lvgl.h"

#include <cstdint>

namespace ui {{
namespace icons {{
{emit("train", TRAIN)}{emit("bus", BUS)}
}}  // namespace icons
}}  // namespace ui
""")
print(f"wrote {out} ({SIDE}x{SIDE}, {len(TRAIN)} bytes each)")
